exclude_paths:
  - db/migrate

Attribute:
  enabled: false

ControlParameter:
  enabled: false

FeatureEnvy:
  enabled: false

IrresponsibleModule:
  enabled: false

TooManyStatements:
  max_statements: 6

UncommunicativeModuleName:
  exclude:
    - V1

UtilityFunction:
  enabled: false
