AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Rails:
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: false

HttpPositionalArguments:
  Enabled: false

HasAndBelongsToMany:
  Enabled: false

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

AmbiguousBlockAssociation:
  Exclude:
    - 'spec/models/task_spec.rb'
