version: 2
jobs:
  build:
    working_directory: ~/todo-list-api

    docker:
      - image: circleci/ruby:2.4.2-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: root
          RAILS_ENV: test

      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: ""

    environment:
      - RAILS_ENV: "test"

    steps:
      - checkout

      - restore_cache:
          keys:
            - test-{{ checksum "Gemfile.lock" }}

      - run:
          name: Installing dependencies
          command: gem install bundler && bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          key: test-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Waiting for Postgresql
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Creating database.yml
          command: cp config/database.sample.yml config/database.yml

      - run:
          name: Creating database
          command: bundle exec rake db:create

      - run:
          name: Loading schema
          command: bundle exec rake db:schema:load

      - run:
          name: RSpec
          command: |
            mkdir /tmp/test-results

            bundle exec rspec --format RspecJunitFormatter \
                              --out /tmp/test-results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
